# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8a1h9yqhIro2zjbcxcTelhhhLpRluT6
"""

# --------------------------
# Task 3 – Data Analysis
# --------------------------

# Import required libraries
import pandas as pd
import numpy as np
import os

# --------------------------
# Load the cleaned CSV from Task 2
# --------------------------
task2_csv = "/content/story_list_20260403_115343.csv"
story_list = pd.read_csv(task2_csv)
story_list

# Quick information
story_list.info()

# dataframe shape
print("Now of Rows ",story_list.shape[0])
print("Now of columns ",story_list.shape[1])

# Convert 'collected_at' to datetime
story_list['collected_at'] = pd.to_datetime(story_list['collected_at'])

# analyse how many posts are there per category?
category_list = story_list.groupby('category')['Post_id'].count().reset_index()
category_list

# Which category has the highest total score?
high_tot_score = story_list.groupby('category')['score'].sum().sort_values(ascending=False).reset_index()
high_tot_score

# Which category has the most comments?
most_comment = story_list.groupby('category')['num_comments'].sum().sort_values(ascending=False).reset_index()
most_comment

# Which post has the highest score?
highscore_post = story_list.nlargest(1, 'score')
highscore_post[['Post_id','title','author','category']]

#Which post has the most comments?
most_comment_post = story_list.nlargest(1, 'num_comments')
most_comment_post[['Post_id','title','author','category']]

# Which post has the highest score per comment (score ÷ num_comments)?
# add new column score per comment
story_list['score_per_comment'] = story_list.apply(
                                     lambda row: row['score'] / row['num_comments']
                                     if row['num_comments'] > 0 else row['score'], axis=1)

highscore_per_comment = story_list.nlargest(1,'score_per_comment')
highscore_per_comment

# Find the post with the least score per comment
least_score_per_comment = story_list.nsmallest(1, 'score_per_comment')

least_score_per_comment

# Which authors have the most posts?
author_post_counts = story_list.groupby('author')['Post_id'].count()

# Find the author with the most posts
most_posts_author = author_post_counts.idxmax().capitalize()
most_posts_count = author_post_counts.max()

print(f"{most_posts_author} has the most posts: {most_posts_count} posts")

# Which authors have the highest average post score?
author_post_score = story_list.groupby('author')['score'].mean()
# Find the author with the highest avg  score
high_avg_score_author = author_post_score.idxmax().capitalize()
high_avg_score = author_post_score.max()
print(f" {high_avg_score_author} :  have the highest average post score: {high_avg_score} posts")

import os
from datetime import datetime

# Ensure the output folder exists
os.makedirs("data", exist_ok=True)

# Create a filename with the current timestamp
filename = f"data/story_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"

# Save the DataFrame to CSV
story_list.to_csv(filename, index=False)

