# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Xa2HWMgNbR_oMJBZn3uao4r5yrmfsKq
"""

# --------------------------
# Task 4 – Visualization
# --------------------------

# Import Required Library
import pandas as pd
import matplotlib.pyplot as plt
import os

# Load Task 3 CSV
task3_csv = "/content/story_analysis_20260403_141604.csv"
story_list = pd.read_csv(task3_csv)

# --------------------------
# Posts per Category
# --------------------------
category_counts = story_list['category'].value_counts()
plt.figure(figsize=(8,4))
category_counts.plot(kind='bar', color='skyblue')
plt.title('Number of Posts per Category')
plt.xlabel('Category')
plt.ylabel('Number of Posts')
plt.xticks(rotation=45)
plt.tight_layout()
os.makedirs("plots", exist_ok=True)
plt.savefig("plots/posts_per_category.png")
plt.show()
plt.close()

# --------------------------
#  Total Score per Category
# --------------------------
score_per_category = story_list.groupby('category')['score'].sum().sort_values(ascending=False)
plt.figure(figsize=(8,5))
score_per_category.plot(kind='bar', color='orange')
plt.title('Total Score per Category')
plt.xlabel('Category')
plt.ylabel('Total Score')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("plots/total_score_per_category.png")
plt.show()
plt.close()

# --------------------------
# Top 10 Authors by Average Score
# --------------------------
author_avg_score = story_list.groupby('author')['score'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,5))
author_avg_score.plot(kind='bar', color='green')
plt.title('Top 10 Authors by Average Score')
plt.xlabel('Author')
plt.ylabel('Average Score')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("plots/top10_authors_avg_score.png")
plt.show()
plt.close()

